export const AVATAR_OPTIONS = [
  'Avatar-1.png',
  'Avatar-2.png',
  'Avatar-3.png',
  'Avatar-4.png',
  'Avatar-5.png',
  'Avatar-6.png',
  'Avatar-7.png',
  'Avatar-8.png',
  'Avatar-9.png',
  'Avatar-10.png',
  'Avatar-11.png',
  'Avatar-12.png',
  'Avatar-13.png',
  'Avatar-14.png',
  'Avatar-15.png',
  'Avatar-16.png',
  'Avatar-17.png',
  'Avatar-18.png',
  'Avatar-19.png',
  'Avatar-20.png',
  'Avatar-21.png',

]